<?php namespace AregoLife\Repsite\Structures;
		use AregoLife\Repsite\TrivialLoader as Loader;
		class EnrollMemberAsOrphan extends Loader {
				public $Token;
public $Context;
public $FirstName;
public $MiddleInitial;
public $LastName;
public $CompanyName;
public $TaxPayerNumber;
public $MailingAddress1;
public $MailingAddress2;
public $MailingCity;
public $MailingState;
public $MailingZip;
public $MailingCountry;
public $BillingAddress1;
public $BillingAddress2;
public $BillingCity;
public $BillingState;
public $BillingZip;
public $BillingCountry;
public $DayPhone;
public $EveningPhone;
public $MobilePhone;
public $Email;
public $CatalogueID;
public $ProductNumber;
public $Price;
public $DealershipTypeCode;
public $MemberEnrollerID;
public $MemberEnrollerPosition;
public $SponsorMemberID;
public $SponsorPosition;
public $BinaryPlacementMemberID;
public $BinaryPlacementPosition;
public $BinaryPlacementLineage;
public $UniPlacementMemberID;
public $UniPlacementPosition;
public $PaymentTypeCode;
public $CardAccountNumber;
public $CVV2Code;
public $CardHolderName;
public $CardExpirationMonth;
public $CardExpirationYear;
public $ShippingCode;
public $ReplicatedWebsiteURL;
public $ReplicatedWebsitePassword;
public $AddlPaymentInfo;
}

